import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const CLIENT_ID=Deno.env.get("MICROSOFT_ONEDRIVE_CLIENT_ID");
const CLIENT_SECRET=Deno.env.get("MICROSOFT_ONEDRIVE_CLIENT_SECRET");
const ENCRYPTION_KEY=Deno.env.get("MICROSOFT_ONEDRIVE_TOKEN_ENCRYPTION_KEY");
const ALLOWED_ORIGIN=Deno.env.get("PORTAL_ALLOWED_ORIGIN")??"https://portal.ca-kka.com";
const corsHeaders={"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const service=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:corsHeaders});
const b64url=(bytes:Uint8Array)=>{let b="";for(const x of bytes)b+=String.fromCharCode(x);return btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")};
const fromB64url=(v:string)=>{const p=v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-(v.length%4))%4);const b=atob(p),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a};
const utf8=(v:string)=>new TextEncoder().encode(v);
async function deriveKey(s:string){const d=await crypto.subtle.digest("SHA-256",utf8(s));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["encrypt","decrypt"])}
async function decryptCredential(blob:string,iv:string,secret:string){const key=await deriveKey(secret);const p=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64url(iv)},key,fromB64url(blob));return JSON.parse(new TextDecoder().decode(new Uint8Array(p)))}
async function encryptCredential(c:unknown,secret:string){const key=await deriveKey(secret),iv=crypto.getRandomValues(new Uint8Array(12)),e=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,utf8(JSON.stringify(c)));return{blob:b64url(new Uint8Array(e)),iv:b64url(iv)}}
async function getUser(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;const {data,error}=await service.auth.getUser(h.slice(7).trim());return error||!data.user?null:data.user}
async function requireStaff(id:string){const {data}=await service.from("profiles").select("role,active").eq("id",id).maybeSingle();return !!data?.active&&["admin","staff"].includes(data.role)}
async function connection(_uid:string){const {data,error}=await service.from("storage_connections").select("id,owner_user_id,provider_email,drive_id,status,credential_blob,credential_iv,scope").eq("provider","onedrive").eq("status","connected").limit(2);if(error||!data?.length)throw new Error("OneDrive is not connected.");if(data.length!==1)throw new Error("Multiple OneDrive connections found; administrator review is required.");const c=data[0];if(!c.credential_blob||!c.credential_iv)throw new Error("OneDrive credentials are unavailable.");return c}
async function saveCredential(id:string,c:unknown){if(!ENCRYPTION_KEY)throw new Error("OneDrive encryption key is not configured.");const e=await encryptCredential(c,ENCRYPTION_KEY);const {error}=await service.from("storage_connections").update({credential_blob:e.blob,credential_iv:e.iv,updated_at:new Date().toISOString(),last_verified_at:new Date().toISOString(),status:"connected"}).eq("id",id);if(error)throw new Error("Unable to update OneDrive credentials.")}
async function graphToken(c:any){if(!CLIENT_ID||!CLIENT_SECRET||!ENCRYPTION_KEY)throw new Error("OneDrive configuration is incomplete.");const cred=await decryptCredential(c.credential_blob,c.credential_iv,ENCRYPTION_KEY);const obtained=Date.parse(String(cred.obtained_at??"2000-01-01T00:00:00.000Z")),expires=Number(cred.expires_in??3600),refresh=!cred.access_token||!Number.isFinite(obtained)||Date.now()>=obtained+expires*1000-120000;if(!refresh)return String(cred.access_token);if(!cred.refresh_token)throw new Error("OneDrive refresh token is unavailable. Reconnect OneDrive.");const r=await fetch("https://login.microsoftonline.com/consumers/oauth2/v2.0/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token:String(cred.refresh_token),grant_type:"refresh_token",scope:"openid profile offline_access User.Read Files.ReadWrite"})}),b=await r.json().catch(()=>({}));if(!r.ok||!b.access_token)throw new Error("OneDrive authorization expired. Reconnect OneDrive.");const next={access_token:String(b.access_token),refresh_token:String(b.refresh_token??cred.refresh_token),token_type:b.token_type??cred.token_type??"Bearer",expires_in:b.expires_in??3600,obtained_at:new Date().toISOString()};await saveCredential(c.id,next);return next.access_token}
async function graph(token:string,path:string,init:RequestInit={}){const r=await fetch(`https://graph.microsoft.com/v1.0${path}`,{...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers??{}),Authorization:`Bearer ${token}`}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error?.message??`Microsoft Graph request failed (${r.status}).`);return b}
const cleanName=(v:string)=>v.trim().replace(/[<>:\"/\\|?*]/g,"-").replace(/\s+/g," ").slice(0,180);
async function ensureFolder(token:string,driveId:string,parentId:string,name:string){const c=await graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(parentId)}/children`);const e=c.value?.find((x:any)=>x.folder&&String(x.name).toLowerCase()===name.toLowerCase());if(e)return e;return graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(parentId)}/children`,{method:"POST",body:JSON.stringify({name,folder:{},"@microsoft.graph.conflictBehavior":"fail"})})}
async function getRoot(token:string,driveId:string){return graph(token,`/drives/${encodeURIComponent(driveId)}/root`)}
async function ensureKkaFolders(token:string,driveId:string){const root=await getRoot(token,driveId),kka=await ensureFolder(token,driveId,root.id,"KKA My Files"),areas=["GST","TDS","Income Tax","Accounts","MCA","Other"],out:any={root:kka};for(const a of areas)out[a]=await ensureFolder(token,driveId,kka.id,a);return out}
async function resolveDestination(token:string,driveId:string,body:any){const folders=await ensureKkaFolders(token,driveId),map:any={gst:"GST",tds:"TDS",income_tax:"Income Tax","income tax":"Income Tax",accounts:"Accounts",mca:"MCA",other:"Other"};const area=map[String(body.area??"Other").trim().toLowerCase()]??"Other";let parent=folders[area];if(body.clientId){const {data:client,error}=await service.from("clients").select("id,legal_name,display_name,pan,gstin,tan,cin").eq("id",String(body.clientId)).maybeSingle();if(error)throw error;if(!client)throw new Error("The selected client does not exist.");parent=await ensureFolder(token,driveId,parent.id,cleanName(String(client.display_name||client.legal_name||client.pan||client.gstin||client.id)))}if(body.financialYear)parent=await ensureFolder(token,driveId,parent.id,cleanName(String(body.financialYear)));if(body.filingPeriod&&(area==="GST"||area==="TDS"))parent=await ensureFolder(token,driveId,parent.id,cleanName(String(body.filingPeriod)));return{parent,area,financialYear:body.financialYear?String(body.financialYear):null,filingPeriod:body.filingPeriod?String(body.filingPeriod):null}}
async function createUploadSession(token:string,driveId:string,parentId:string,filename:string){const safe=cleanName(filename);return graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(parentId)}:/${encodeURIComponent(safe)}:/createUploadSession`,{method:"POST",body:JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"rename",name:safe}})})}
async function registerItem(uid:string,driveId:string,body:any){const id=String(body.driveItemId??"");if(!id)throw new Error("driveItemId is required.");const c=await connection(uid),token=await graphToken(c),item=await graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(id)}`),{data,error}=await service.from("onedrive_file_registry").upsert({owner_user_id:c.owner_user_id,drive_id:driveId,drive_item_id:id,parent_drive_item_id:body.parentDriveItemId??null,name:item.name??body.name??"Unnamed file",one_drive_path:body.oneDrivePath??null,web_url:item.webUrl??body.webUrl??null,client_id:body.clientId??null,area:body.area??null,financial_year:body.financialYear??null,filing_period:body.filingPeriod??null,classification_status:body.classificationStatus??"classified",updated_at:new Date().toISOString()},{onConflict:"drive_id,drive_item_id"}).select().single();if(error)throw new Error("The OneDrive file was uploaded, but KKA could not register its metadata.");return data}
async function uploadFromSupabase(uid:string,driveId:string,body:any){const storagePath=String(body.storagePath??"").trim(),filename=String(body.filename??"").trim();if(!storagePath||!filename)throw new Error("storagePath and filename are required.");const c=await connection(uid),token=await graphToken(c),destination=await resolveDestination(token,driveId,body),{data:file,error}=await service.storage.from("client-documents").download(storagePath);if(error||!file)throw new Error(`Unable to read the reviewed document from storage: ${error?.message??"file not found"}`);const bytes=new Uint8Array(await file.arrayBuffer());if(!bytes.length)throw new Error("The reviewed document is empty.");const session=await createUploadSession(token,driveId,destination.parent.id,filename);if(!session.uploadUrl)throw new Error("Microsoft did not return an upload URL.");const chunkSize=10*1024*1024;let uploaded:any=null;for(let start=0;start<bytes.length;start+=chunkSize){const end=Math.min(start+chunkSize,bytes.length),chunk=bytes.slice(start,end),r=await fetch(session.uploadUrl,{method:"PUT",headers:{"Content-Length":String(chunk.byteLength),"Content-Range":`bytes ${start}-${end-1}/${bytes.length}`},body:chunk}),b=await r.json().catch(()=>null);if(!r.ok&&r.status!==202)throw new Error(b?.error?.message??`OneDrive upload failed (${r.status}).`);if(r.status===200||r.status===201)uploaded=b}if(!uploaded?.id)throw new Error("OneDrive upload did not return the completed file item.");const registry=await registerItem(uid,driveId,{driveItemId:uploaded.id,parentDriveItemId:destination.parent.id,name:uploaded.name??filename,webUrl:uploaded.webUrl??null,clientId:body.clientId??null,area:body.area??null,financialYear:body.financialYear??null,filingPeriod:body.filingPeriod??null,classificationStatus:"classified"});return{item:uploaded,registry,destination:{parentDriveItemId:destination.parent.id,area:destination.area,financialYear:destination.financialYear,filingPeriod:destination.filingPeriod}}}
async function listDirectory(token:string,driveId:string,body:any){const destination=await resolveDestination(token,driveId,body);const children=await graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(destination.parent.id)}/children?$top=200`);return{destination:{parentDriveItemId:destination.parent.id,area:destination.area,financialYear:destination.financialYear,filingPeriod:destination.filingPeriod},files:(children.value??[]).map((x:any)=>({id:x.id,name:x.name,size:x.size??0,webUrl:x.webUrl??null,createdDateTime:x.createdDateTime??null,lastModifiedDateTime:x.lastModifiedDateTime??null,isFolder:!!x.folder,file:!!x.file}))}}
async function deleteItem(uid:string,token:string,driveId:string,driveItemId:string){if(!driveItemId)throw new Error("driveItemId is required.");const c=await connection(uid);await graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(driveItemId)}`,{method:"DELETE"});await service.from("onedrive_file_registry").delete().eq("owner_user_id",c.owner_user_id).eq("drive_id",driveId).eq("drive_item_id",driveItemId);return{deleted:true,driveItemId}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"POST requests only."},405);try{const user=await getUser(req);if(!user)return json({error:"Authentication required."},401);if(!(await requireStaff(user.id)))return json({error:"Staff access required."},403);const body=await req.json().catch(()=>({})),op=String(body.operation??"status");if(op==="status"){const c=await connection(user.id);return json({connected:true,provider:"onedrive",providerEmail:c.provider_email,driveId:c.drive_id,status:c.status})}const c=await connection(user.id),token=await graphToken(c),driveId=c.drive_id;if(!driveId)throw new Error("OneDrive drive ID is missing. Reconnect OneDrive.");if(op==="bootstrap")return json({success:true,folders:await ensureKkaFolders(token,driveId)});if(op==="create_upload_session"){const d=await resolveDestination(token,driveId,body),s=await createUploadSession(token,driveId,d.parent.id,String(body.filename??""));return json({success:true,uploadUrl:s.uploadUrl,expirationDateTime:s.expirationDateTime,parentDriveItemId:d.parent.id,area:d.area,financialYear:d.financialYear,filingPeriod:d.filingPeriod})}if(op==="upload_from_supabase")return json({success:true,...await uploadFromSupabase(user.id,driveId,body)});if(op==="register_item")return json({success:true,registry:await registerItem(user.id,driveId,body)});if(op==="get_item")return json({success:true,item:await graph(token,`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(String(body.driveItemId??""))}`)});if(op==="list_directory")return json({success:true,...await listDirectory(token,driveId,body)});if(op==="delete_item")return json({success:true,...await deleteItem(user.id,token,driveId,String(body.driveItemId??""))});if(op==="list_registry"){const {data,error}=await service.from("onedrive_file_registry").select("id,name,one_drive_path,web_url,client_id,area,financial_year,filing_period,classification_status,created_at,updated_at").eq("owner_user_id",c.owner_user_id).order("created_at",{ascending:false}).limit(200);if(error)throw new Error("Unable to load the OneDrive file registry.");return json({success:true,files:data??[]})}return json({error:"Unsupported operation."},400)}catch(error){console.error("onedrive-storage error",error);return json({error:error instanceof Error?error.message:"OneDrive storage operation failed."},500)}});