import { corsHeaders, json, requireStaff } from "../_shared/portal.ts";
const clean=(v:unknown)=>String(v??"").trim();
const upper=(v:unknown)=>clean(v).toUpperCase()||null;
async function requireAdmin(req:Request){const {user,service}=await requireStaff(req);const {data:p}=await service.from("profiles").select("role,active").eq("id",user.id).maybeSingle();if(!p?.active||p.role!=="admin")throw new Error("Admin access required");return{user,service}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{const{service}=await requireAdmin(req),b=await req.json(),action=clean(b.action),accountId=clean(b.accountId),clientId=clean(b.clientId);
if(action==="list"){let account;if(accountId){const{data,error}=await service.from("client_accounts").select("id,account_name,primary_client_id,active,created_at,updated_at").eq("id",accountId).maybeSingle();if(error)throw error;account=data}else if(clientId){const{data,error}=await service.from("client_accounts").select("id,account_name,primary_client_id,active,created_at,updated_at").eq("primary_client_id",clientId).maybeSingle();if(error)throw error;account=data}if(!account)return json({error:"Client account not found"},404);const{data:members,error:me}=await service.from("client_account_members").select("account_id,client_id,relationship,is_primary,active,created_at,updated_at,clients(id,legal_name,display_name,pan,tan,cin,gstin,mobile,active)").eq("account_id",account.id).order("is_primary",{ascending:false}).order("created_at",{ascending:true});if(me)throw me;return json({account,members:members??[]})}
if(action==="search_existing"){const q=clean(b.query);if(q.length<2)return json({profiles:[]});const esc=q.replace(/[%_]/g,m=>`\\${m}`);const{data,error}=await service.from("clients").select("id,legal_name,display_name,pan,tan,cin,gstin,mobile,active").eq("active",true).or(`legal_name.ilike.%${esc}%,display_name.ilike.%${esc}%,pan.ilike.%${esc}%,tan.ilike.%${esc}%,cin.ilike.%${esc}%,gstin.ilike.%${esc}%`).limit(20);if(error)throw error;return json({profiles:data??[]})}
if(action==="add_existing"){if(!accountId||!clientId)return json({error:"accountId and clientId are required"},400);const{data:account}=await service.from("client_accounts").select("id,primary_client_id,active").eq("id",accountId).maybeSingle();if(!account?.active)return json({error:"Client account not found or inactive"},404);if(account.primary_client_id===clientId)return json({error:"This profile is already the primary holder"},409);const{data:client}=await service.from("clients").select("id,active").eq("id",clientId).maybeSingle();if(!client?.active)return json({error:"Existing client profile not found or inactive"},404);const{data:existing}=await service.from("client_account_members").select("account_id").eq("account_id",accountId).eq("client_id",clientId).maybeSingle();if(existing)return json({error:"This profile is already linked to the family account"},409);const{data:member,error}=await service.from("client_account_members").insert({account_id:accountId,client_id:clientId,relationship:clean(b.relationship)||"family_member",is_primary:false,active:true}).select().single();if(error)throw error;return json({member})}
if(action==="create_new"||action==="create_family_member"){const legalName=clean(b.legalName),displayName=clean(b.displayName),pan=upper(b.pan),tan=upper(b.tan),cin=upper(b.cin),gstin=upper(b.gstin),mobile=clean(b.mobile)||null,aliases=clean(b.aliases),relationship=clean(b.relationship)||"family_member";if(!accountId||!legalName)return json({error:"accountId and legalName are required"},400);if(![pan,tan,cin,gstin].some(Boolean))return json({error:"At least one PAN, TAN, CIN or GSTIN is required"},400);const{data:account}=await service.from("client_accounts").select("id,active,primary_client_id").eq("id",accountId).maybeSingle();if(!account?.active)return json({error:"Client account not found or inactive"},404);const{data:client,error:ce}=await service.from("clients").insert({legal_name:legalName,display_name:displayName||null,pan,tan,cin,gstin,mobile,active:true,filename_aliases:aliases?aliases.split(",").map(clean).filter(Boolean):[]}).select("id,legal_name,display_name,pan,tan,cin,gstin,mobile,active").single();if(ce)throw ce;const{data:member,error:me}=await service.from("client_account_members").insert({account_id:account.id,client_id:client.id,relationship,is_primary:false,active:true}).select().single();if(me){await service.from("clients").delete().eq("id",client.id);throw me}return json({client,member,accountId:account.id,primaryClientId:account.primary_client_id,loginCreated:false})}
if(action==="remove"||action==="deactivate_member"){if(!accountId||!clientId)return json({error:"accountId and clientId are required"},400);const{data:member}=await service.from("client_account_members").select("is_primary").eq("account_id",accountId).eq("client_id",clientId).maybeSingle();if(!member)return json({error:"Family profile link not found"},404);if(member.is_primary)return json({error:"The primary holder cannot be changed through this action"},409);if(action==="remove"){const{error}=await service.from("client_account_members").delete().eq("account_id",accountId).eq("client_id",clientId);if(error)throw error}else{const{error}=await service.from("client_account_members").update({active:false,updated_at:new Date().toISOString()}).eq("account_id",accountId).eq("client_id",clientId);if(error)throw error}return json({success:true})}
return json({error:"Unsupported action"},400)}catch(e){return json({error:e instanceof Error?e.message:"Family management operation failed"},400)}});
