const categories=[['GST','Goods & Services Tax'],['Income Tax','Direct tax updates'],['TDS / TCS','Withholding tax'],['MCA','Companies & LLP compliance'],['Audit & Accounting','Standards & practice'],['FEMA / RBI','Foreign exchange & banking'],['SEBI','Capital markets & regulation'],['Case Laws','Judgments & rulings'],['Compliance','Due dates & action points'],['Practical Guides','Step-by-step resources'],['FAQs','Common professional questions']];
const articles=[
 {title:'KKA Knowledge Centre is coming soon',category:'KKA Updates',summary:'A dedicated home for KKA insights, regulatory updates, case-law analysis and practical compliance guidance.',date:'2026-09-07',author:'KKA'},
 {title:'Latest regulatory updates from trusted sources',category:'Regulatory Updates',summary:'Follow KKA for curated developments across GST, Income Tax, TDS, MCA, SEBI, RBI and other regulatory areas.',date:'2026-09-07',author:'KKA'}
];
const catEl=document.getElementById('categories');const artEl=document.getElementById('articles');const search=document.getElementById('search');const count=document.getElementById('count');
function renderCats(){catEl.innerHTML=categories.map(c=>`<a class="category" href="#latest"><span>${c[0]}</span><small>${c[1]}</small></a>`).join('')}
function renderArticles(q=''){const s=q.trim().toLowerCase();const rows=articles.filter(a=>!s||[a.title,a.category,a.summary,a.author].join(' ').toLowerCase().includes(s));count.textContent=`${rows.length} item${rows.length===1?'':'s'}`;artEl.innerHTML=rows.length?rows.map(a=>`<article class="article"><div class="article-body"><span class="tag">${a.category}</span><h3>${a.title}</h3><p>${a.summary}</p><div class="meta">${a.author} · ${new Date(a.date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</div></div></article>`).join(''):'<p class="muted">No matching knowledge items found.</p>'}
renderCats();renderArticles();search.addEventListener('input',e=>renderArticles(e.target.value));
