import { createClient as createSupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "../config.js";
const supabase=createSupabaseClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const MARKER="kka-tab-session:client";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function stableSession(){for(let i=0;i<4;i++){const {data:{session}}=await supabase.auth.getSession();if(session?.user)return session;if(i<3)await sleep(250)}return null}
async function profile(id){for(let i=0;i<3;i++){const {data,error}=await supabase.from("profiles").select("role,active").eq("id",id).maybeSingle();if(!error&&data)return data;if(i<2)await sleep(250)}return null}
async function root(){try{sessionStorage.removeItem(MARKER)}catch{};window.location.replace("../")}
async function boot(){const session=await stableSession();if(!session?.user)return root();const p=await profile(session.user.id);if(!p?.active){await supabase.auth.signOut({scope:"local"}).catch(()=>{});return root()}if(p.role!=="client"){window.location.replace(p.role==="admin"||p.role==="staff"?"../admin/":"../");return}try{sessionStorage.setItem(MARKER,String(Date.now()));sessionStorage.setItem("kka-auth-handoff","client")}catch{};await import("../diagnostic-logger.js?v=20260924-authbridge1");await import("../theme.js?v=20260914-2");await import("../operation-feedback.js?v=20260915-2");await import("../session-route-transition.js?v=20260918-route4");await import("../session-security.js?v=20260924-authbridge1");await import("../session-settings.js?v=20260918-session-settings2");await import("../dashboard-live.js?v=20260915-countfix1");await import("../family-management.js?v=20260918-family1");await import("../family-switcher.js?v=20260911-2");await import("../family-profile-context.js?v=20260911-1");await import("../client-upload-view.js?v=20260918-upload2");await import("../upload-network-resilience.js?v=20260915-uploadres1");await import("../family-documents-view.js?v=20260920-docs7");await import("../client-dashboard-v2.js?v=20260918-clientready4");await import("../client-profile-menu.js?v=20260918-profile1");await import("../client-profile-sync.js?v=20260916-profile-sync1");await import("../client-navigation-guard.js?v=20260918-nav1");await import("../mobile-menu.js?v=20260916-menu1");await import("../client-portal-feedback.js?v=20260916-client-feedback3");await import("../app.js?v=20260920-2fa1")}
void boot().catch(e=>{console.error("[KKA auth bridge] client bootstrap failed",e);try{window.KKALog?.error?.("auth_bridge_boot","Client portal core bootstrap failed",{message:e?.message||String(e)})}catch{}});
