import { createClient as createSupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const supabase=createSupabaseClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),root=document.querySelector("#app");
const template=id=>document.querySelector(id).content.cloneNode(true);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let currentProfile=null,currentUser=null;
const notify=(type,message,detail="")=>{try{window.KKANotify?.[type]?.(message,detail)}catch{}};
async function signOut(){await supabase.auth.signOut();currentUser=null;currentProfile=null;renderLogin()}
function setupPasswordToggle(){const input=document.querySelector("#password"),toggle=document.querySelector("#password-toggle");if(!input||!toggle)return;toggle.addEventListener("click",()=>{const visible=input.type==="text";input.type=visible?"password":"text";toggle.textContent=visible?"Show":"Hide";toggle.setAttribute("aria-label",visible?"Show password":"Hide password");toggle.setAttribute("aria-pressed",String(!visible));input.focus()})}
function renderLogin(){root.replaceChildren(template("#login-template"));setupPasswordToggle();document.querySelector("#login-form").addEventListener("submit",async e=>{e.preventDefault();const m=document.querySelector("#auth-message");m.textContent="Signing in…";const {error}=await supabase.auth.signInWithPassword({email:document.querySelector("#email").value,password:document.querySelector("#password").value});if(error){m.textContent="Unable to sign in. Check your credentials or contact KKA.";notify("error",error.message||"Unable to sign in.");return}await renderPortal()})}
function navSetup(){document.querySelectorAll(".sidebar nav a").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();a.dataset.view==="clients"?renderClients():renderDashboard()}))}
async function renderPortal(){root.replaceChildren(template("#portal-template"));const {data:{user}}=await supabase.auth.getUser();currentUser=user;if(!user){renderLogin();return}const {data:profile}=await supabase.from("profiles").select("role,full_name,active").eq("id",user.id).maybeSingle();currentProfile=profile;if(!profile?.active){await supabase.auth.signOut();renderLogin();return}const staff=["admin","staff"].includes(profile.role);document.querySelectorAll(".staff-only").forEach(x=>x.hidden=!staff);navSetup();await renderDashboard()}
async function resolveReview(documentId){const clientId=prompt("Enter the approved client UUID.");if(!clientId)return;const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){notify("error","The session has expired. Please sign in again.");return}const r=await fetch(`${SUPABASE_URL}/functions/v1/resolve-review`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({documentId,clientId,area:"other",action:"accept"})});const d=await r.json().catch(()=>({}));if(!r.ok){notify("error",d.error||`The review could not be completed (HTTP ${r.status}).`);return}notify("success","Review completed successfully.");await renderDashboard()}
async function manageClient(clientId,action,payload={}){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){notify("error","The session has expired. Please sign in again.");return null}const r=await fetch(`${SUPABASE_URL}/functions/v1/manage-client-account-v2`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({clientId,action,...payload})});const result=await r.json().catch(()=>({}));if(!r.ok){notify("error",result.error||`Client management action failed (HTTP ${r.status}).`);return null}return result}
