import { createClient as createSupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const supabase=createSupabaseClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const emailRowStyle=document.createElement("style");emailRowStyle.textContent='.client-email-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important}.client-email-row input{width:100%!important}.client-email-row button{width:auto!important;min-width:100px!important}@media(max-width:460px){.client-email-row{grid-template-columns:1fr!important}.client-email-row button{width:100%!important}}';document.head.appendChild(emailRowStyle);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const clean=v=>String(v??"").trim();
async function session(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("The session has expired. Please sign in again.");return session.access_token}
async function callFamily(payload){const token=await session();const r=await fetch(`${SUPABASE_URL}/functions/v1/manage-client-family`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||"Family account operation failed.");return data}
async function createAccount(payload){const token=await session();const r=await fetch(`${SUPABASE_URL}/functions/v1/create-client-account`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||"Client account could not be created.");return data}
async function verifyEmail(email){const {data,error}=await supabase.rpc("resolve_client_email_account",{p_email:email});if(error)throw new Error(error.message||"Email could not be checked.");return data||{linked:false,message:"Email could not be checked."}}
function modal(inner){const m=document.createElement("div");m.className="modal-backdrop client-login-modal-backdrop";m.innerHTML=`<section class="modal" role="dialog" aria-modal="true">${inner}</section>`;document.body.appendChild(m);m.querySelectorAll(".modal-close").forEach(b=>b.addEventListener("click",()=>m.remove()));return m}
function show(){const m=modal(`<div class="modal-head"><div><p class="eyebrow">NEW CLIENT</p><h2>Create client profile</h2><p class="muted">Enter the login email and check it before creating the profile.</p></div><button class="modal-close" type="button">×</button></div><form id="client-login-form"><div class="form-grid"><label class="full client-email-field">Login email<div class="client-email-row"><input name="email" type="email" required autocomplete="email" placeholder="client@example.com"><button type="button" class="secondary" id="verify-email"><span class="check-spinner" aria-hidden="true"></span><span class="check-label">✓ Check</span></button></div></label><div class="form-message full" id="email-status">Email must be checked before the profile can be created.</div><div class="full" id="holder-status" hidden></div><label>Legal name<input name="legalName" required maxlength="200"></label><label>Display name<input name="displayName" maxlength="200"></label><label>Full name<input name="fullName" maxlength="200"></label><label>Mobile<input name="mobile" type="tel" maxlength="20" placeholder="+91 98765 43210"></label><label>PAN<input name="pan" maxlength="10"></label><label>TAN<input name="tan" maxlength="10"></label><label>CIN<input name="cin" maxlength="21"></label><label>GSTIN<input name="gstin" maxlength="15"></label><label class="full">Filename aliases<input name="aliases" placeholder="Name variants, separated by commas"></label><label class="check"><input name="canUpload" type="checkbox"> Allow client uploads</label><label class="full" id="password-row">Initial password<input name="password" type="password" minlength="10" maxlength="72" autocomplete="new-password"></label></div><div class="form-message" id="client-message"></div><div class="modal-actions"><button type="button" class="secondary modal-close">Cancel</button><button class="primary" id="create-client-submit" type="submit" disabled>Create profile</button></div></form>`);const form=m.querySelector("#client-login-form"),email=m.querySelector('[name="email"]'),check=m.querySelector("#verify-email"),spinner=m.querySelector(".check-spinner"),checkLabel=m.querySelector(".check-label"),status=m.querySelector("#email-status"),holder=m.querySelector("#holder-status"),passwordRow=m.querySelector("#password-row"),password=m.querySelector('[name="password"]'),submit=m.querySelector("#create-client-submit"),message=m.querySelector("#client-message");let verifiedEmail="",linkedAccount=null;
email.addEventListener("input",()=>{verifiedEmail="";linkedAccount=null;submit.disabled=true;check.disabled=false;check.className="secondary";spinner.classList.remove("is-spinning");checkLabel.textContent="✓ Check";status.textContent="Email must be checked before the profile can be created.";holder.hidden=true;holder.innerHTML="";passwordRow.hidden=false;password.required=false;submit.textContent="Create profile"});
check.addEventListener("click",async()=>{const value=clean(email.value).toLowerCase();if(!value||!email.checkValidity()){status.textContent="Enter a valid email address first.";return}check.disabled=true;check.className="secondary processing";spinner.classList.add("is-spinning");checkLabel.textContent="Checking…";status.textContent="Checking email…";holder.hidden=true;try{const data=await verifyEmail(value);verifiedEmail=value;spinner.classList.remove("is-spinning");checkLabel.textContent="✓ Verified";check.className="primary";submit.disabled=false;if(data.linked){linkedAccount=data;holder.hidden=false;holder.innerHTML=`<div class="message"><strong>✓ Primary account holder:</strong> ${esc(data.primaryHolder)}${data.accountName?` <span class="muted">· ${esc(data.accountName)}</span>`:""}</div>`;status.textContent="This email is linked to an existing KKA family account. No separate login will be created.";passwordRow.hidden=true;password.required=false;submit.textContent="Add to family account"}else{linkedAccount=null;status.textContent=data.message||"Email is available for a new KKA primary account.";passwordRow.hidden=false;password.required=true;submit.textContent="Create client login"}}catch(e){verifiedEmail="";linkedAccount=null;submit.disabled=true;check.disabled=false;check.className="secondary";spinner.classList.remove("is-spinning");checkLabel.textContent="✓ Check";status.textContent=e.message}finally{check.disabled=false;spinner.classList.remove("is-spinning")}});
form.addEventListener("submit",async e=>{e.preventDefault();if(!verifiedEmail||verifiedEmail!==clean(email.value).toLowerCase()){status.textContent="Please check the email address before creating the profile.";return}const d=new FormData(form);const base={legalName:clean(d.get("legalName")),displayName:clean(d.get("displayName")),fullName:clean(d.get("fullName")),mobile:clean(d.get("mobile")),pan:clean(d.get("pan")),tan:clean(d.get("tan")),cin:clean(d.get("cin")),gstin:clean(d.get("gstin")),aliases:clean(d.get("aliases"))};submit.disabled=true;message.textContent=linkedAccount?"Adding family profile…":"Creating client login…";try{if(linkedAccount){await callFamily({action:"create_family_member",accountId:linkedAccount.accountId,...base});message.textContent="Family profile added successfully. No separate login was created."}else{await createAccount({...base,email:verifiedEmail,password:String(d.get("password")||""),canUpload:d.get("canUpload")==="on"});message.textContent="Client login created successfully."}setTimeout(()=>{m.remove();document.getElementById("refresh-clients")?.click()},600)}catch(err){message.textContent=err.message;submit.disabled=false}})}
document.addEventListener("click",e=>{const b=e.target.closest("#new-client");if(!b)return;e.preventDefault();e.stopPropagation();show()},true);
