import { createClient as createSupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const supabase=createSupabaseClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const root=document.querySelector("#app");
let refreshTimer=null;
let observer=null;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function formatSize(bytes){const n=Number(bytes)||0;if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;if(n<1024**3)return`${(n/1024**2).toFixed(1)} MB`;return`${(n/1024**3).toFixed(2)} GB`}
function installStyles(){if(document.querySelector("#storage-monitor-styles"))return;const style=document.createElement("style");style.id="storage-monitor-styles";style.textContent=`
.storage-monitor{margin-top:20px;padding:22px;border:1px solid var(--border);border-radius:18px;background:linear-gradient(135deg,var(--surface),var(--surface-2));box-shadow:var(--shadow)}
.storage-monitor .sm-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.storage-monitor .sm-title{display:flex;align-items:center;gap:10px}.storage-monitor .sm-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:var(--brand-soft,#e8f1ed);color:var(--accent);font-size:18px}.storage-monitor h2{margin:0;font-size:18px}.storage-monitor .sm-value{font-size:30px;font-weight:750;letter-spacing:-.03em;margin-top:14px;color:var(--text)}.storage-monitor .sm-sub{margin-top:3px;font-size:13px}.storage-monitor .sm-track{height:10px;background:var(--border);border-radius:999px;overflow:hidden;margin-top:16px}.storage-monitor .sm-bar{height:100%;border-radius:999px;background:var(--accent);transition:width .25s ease}.storage-monitor[data-level="warning"] .sm-bar{background:var(--warning)}.storage-monitor[data-level="critical"] .sm-bar{background:#dc5b4f}.storage-monitor .sm-foot{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:10px;font-size:12px}.storage-monitor .sm-status{font-weight:650}.storage-monitor .sm-refresh{border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:8px;cursor:pointer;padding:7px 10px;font:600 12px inherit}.storage-monitor .sm-refresh:hover{background:var(--surface-2)}.storage-monitor .sm-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:17px}.storage-monitor .sm-meta div{padding:11px 12px;border-radius:12px;background:color-mix(in srgb,var(--surface-2) 86%,transparent)}.storage-monitor .sm-meta span{display:block;font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--text-muted)}.storage-monitor .sm-meta strong{display:block;margin-top:3px;font-size:14px;color:var(--text)}.storage-monitor .sm-note{margin:15px 0 0;font-size:12px;line-height:1.5;color:var(--text-muted)}@media(max-width:600px){.storage-monitor .sm-meta{grid-template-columns:1fr}.storage-monitor{padding:18px}}
`;document.head.appendChild(style)}
async function isAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return false;const {data:profile}=await supabase.from("profiles").select("role,active").eq("id",user.id).maybeSingle();return profile?.active===true&&profile.role==="admin"}
async function loadUsage(panel){const button=panel.querySelector(".sm-refresh");if(button)button.disabled=true;try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Session expired");const response=await fetch(`${SUPABASE_URL}/functions/v1/onedrive-directory`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({operation:"storage_usage"})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Unable to read OneDrive storage usage");const used=Number(result.quota?.used||0),total=Number(result.quota?.total||0),remaining=Number(result.quota?.remaining||0);if(!total)throw new Error("OneDrive quota information is unavailable");const pct=Math.min(100,Math.max(0,used/total*100)),warning=80,critical=95,displayPct=pct.toFixed(pct>=10?0:1),level=pct>=critical?"critical":pct>=warning?"warning":"normal";panel.dataset.level=level;panel.querySelector(".sm-value").textContent=`${formatSize(used)} used`;panel.querySelector(".sm-sub").textContent=`${displayPct}% of ${formatSize(total)} OneDrive capacity`;panel.querySelector(".sm-bar").style.width=`${pct}%`;panel.querySelector(".sm-percent").textContent=`${displayPct}%`;panel.querySelector(".sm-status").textContent=level==="critical"?"Critical — OneDrive is nearly full":level==="warning"?"Warning — plan ahead for storage":"Healthy — OneDrive has room`;panel.querySelector(".sm-used").textContent=formatSize(used);panel.querySelector(".sm-remaining").textContent=formatSize(remaining);panel.querySelector(".sm-drive-name").textContent=result.drive?.name||"OneDrive";panel.querySelector(".sm-updated").textContent=`Updated ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`}catch(error){panel.dataset.level="warning";panel.querySelector(".sm-value").textContent="OneDrive storage unavailable";panel.querySelector(".sm-sub").textContent=esc(error.message||"Unable to load OneDrive capacity.");panel.querySelector(".sm-bar").style.width="0%";panel.querySelector(".sm-status").textContent="Check failed — retry"}finally{if(button)button.disabled=false}}
function renderPanel(){const main=document.querySelector(".portal-main"),stats=main?.querySelector(".stats");if(!main||!stats||!root||root.querySelector(".storage-monitor"))return;installStyles();const panel=document.createElement("section");panel.className="storage-monitor";panel.innerHTML=`<div class="sm-head"><div><div class="sm-title"><span class="sm-icon">▣</span><div><p class="eyebrow">ONEDRIVE STORAGE</p><h2>Storage health</h2></div></div><div class="sm-value">Checking…</div><div class="sm-sub muted">Reading connected OneDrive capacity</div></div><button class="sm-refresh" type="button">Refresh</button></div><div class="sm-track" aria-label="OneDrive storage usage"><div class="sm-bar" style="width:0%"></div></div><div class="sm-foot"><span class="sm-status">Checking OneDrive…</span><strong class="sm-percent">—</strong></div><div class="sm-meta"><div><span>Used</span><strong class="sm-used">—</strong></div><div><span>Remaining</span><strong class="sm-remaining">—</strong></div></div><p class="sm-note">This is the real quota reported by the connected Microsoft OneDrive account, not Supabase Storage. <strong class="sm-drive-name">OneDrive</strong> is the backing document store.</p><div class="sm-foot"><span class="sm-updated">Not updated yet</span><span>Admin only</span></div>`;stats.insertAdjacentElement("afterend",panel);panel.querySelector(".sm-refresh").addEventListener("click",()=>loadUsage(panel));loadUsage(panel)}
async function tick(){if(!(await isAdmin()))return;renderPanel()}
function start(){if(refreshTimer)clearInterval(refreshTimer);if(observer)observer.disconnect();observer=new MutationObserver(()=>{void tick()});observer.observe(root,{childList:true,subtree:true});void tick();refreshTimer=setInterval(()=>{void tick()},5*60*1000)}
start();
