import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,CID=Deno.env.get("MICROSOFT_ONEDRIVE_CLIENT_ID"),SECRET=Deno.env.get("MICROSOFT_ONEDRIVE_CLIENT_SECRET"),ENC=Deno.env.get("MICROSOFT_ONEDRIVE_TOKEN_ENCRYPTION_KEY");
const origin=Deno.env.get("PORTAL_ALLOWED_ORIGIN")??"https://portal.ca-kka.com";const cors={"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};const service=createClient(URL,KEY,{auth:{autoRefreshToken:false,persistSession:false}});const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const b64=(v:string)=>{const p=v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-v.length%4)%4);const b=atob(p),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a};
async function key(s:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["decrypt"])}
async function credential(blob:string,iv:string){if(!ENC)throw new Error("OneDrive encryption is not configured.");const k=await key(ENC),p=await crypto.subtle.decrypt({name:"AES-GCM",iv:b64(iv)},k,b64(blob));return JSON.parse(new TextDecoder().decode(new Uint8Array(p)))}
async function token(c:any){if(!CID||!SECRET||!ENC)throw new Error("OneDrive configuration is incomplete.");const v=await credential(c.credential_blob,c.credential_iv);const obtained=Date.parse(String(v.obtained_at??"2000-01-01T00:00:00Z")),expires=Number(v.expires_in??3600);if(v.access_token&&Number.isFinite(obtained)&&Date.now()<obtained+expires*1000-120000)return String(v.access_token);if(!v.refresh_token)throw new Error("OneDrive authorization expired. Reconnect OneDrive.");const r=await fetch("https://login.microsoftonline.com/consumers/oauth2/v2.0/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({client_id:CID,client_secret:SECRET,refresh_token:String(v.refresh_token),grant_type:"refresh_token",scope:"openid profile offline_access User.Read Files.ReadWrite"})});const b=await r.json().catch(()=>({}));if(!r.ok||!b.access_token)throw new Error("OneDrive authorization expired. Reconnect OneDrive.");return String(b.access_token)}
async function graph(t:string,path:string,init:RequestInit={}){const r=await fetch(`https://graph.microsoft.com/v1.0${path}`,{...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),Authorization:`Bearer ${t}`}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error?.message??`Microsoft Graph request failed (${r.status}).`);return b}
const clean=(v:string)=>v.trim().replace(/[<>:\\"/|?*]/g,"-").replace(/\s+/g," ").slice(0,180);
async function folder(t:string,d:string,p:string,n:string){const q=await graph(t,`/drives/${encodeURIComponent(d)}/items/${encodeURIComponent(p)}/children?$top=200`);const hit=(q.value??[]).find((x:any)=>x.folder&&String(x.name).toLowerCase()===n.toLowerCase());if(hit)return hit;return graph(t,`/drives/${encodeURIComponent(d)}/items/${encodeURIComponent(p)}/children`,{method:"POST",body:JSON.stringify({name:n,folder:{},"@microsoft.graph.conflictBehavior":"fail"})})}
async function destination(t:string,d:string,nodeId:string,clientId:string,fy:string|null,period:string|null){const root=await graph(t,`/drives/${encodeURIComponent(d)}/root`);let p=await folder(t,d,root.id,"KKA My Files");const chain:any[]=[];let cur=nodeId;for(let i=0;i<20&&cur;i++){const {data:n,error}=await service.from("filing_nodes").select("id,parent_id,name,enabled").eq("id",cur).maybeSingle();if(error)throw error;if(!n||!n.enabled)throw new Error("Filing folder is unavailable.");chain.unshift(n);cur=n.parent_id}for(const n of chain)p=await folder(t,d,p.id,clean(n.name));const {data:c,error}=await service.from("clients").select("id,legal_name,display_name,pan,gstin,tan,cin").eq("id",clientId).eq("active",true).maybeSingle();if(error)throw error;if(!c)throw new Error("Selected client does not exist.");p=await folder(t,d,p.id,clean(String(c.display_name||c.legal_name||c.pan||c.gstin||c.tan||c.cin||c.id)));if(fy)p=await folder(t,d,p.id,clean(fy));if(period)p=await folder(t,d,p.id,clean(period));return p}
async function uploadFromSupabase(uid:string,b:any){const {data:c,error}=await service.from("storage_connections").select("id,drive_id,credential_blob,credential_iv,status").eq("owner_user_id",uid).eq("provider","onedrive").maybeSingle();if(error||!c||c.status!=="connected"||!c.drive_id||!c.credential_blob||!c.credential_iv)throw new Error("OneDrive is not connected.");const t=await token(c);const file=await service.storage.from("client-documents").download(String(b.storagePath));if(file.error||!file.data)throw new Error("Unable to read the uploaded document from storage.");const bytes=new Uint8Array(await file.data.arrayBuffer());if(!bytes.length)throw new Error("The uploaded document is empty.");const p=await destination(t,c.drive_id,String(b.filingNodeId),String(b.clientId),b.financialYear?String(b.financialYear):null,b.filingPeriod?String(b.filingPeriod):null);const name=clean(String(b.filename));const session=await graph(t,`/drives/${encodeURIComponent(c.drive_id)}/items/${encodeURIComponent(p.id)}:/${encodeURIComponent(name)}:/createUploadSession`,{method:"POST",body:JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"rename",name}})});if(!session.uploadUrl)throw new Error("Microsoft did not return an upload URL.");const chunk=10*1024*1024;let item:any=null;for(let s=0;s<bytes.length;s+=chunk){const e=Math.min(s+chunk,bytes.length),part=bytes.slice(s,e),r=await fetch(session.uploadUrl,{method:"PUT",headers:{"Content-Length":String(part.byteLength),"Content-Range":`bytes ${s}-${e-1}/${bytes.length}`},body:part}),x=await r.json().catch(()=>null);if(!r.ok&&r.status!==202)throw new Error(x?.error?.message??`OneDrive upload failed (${r.status}).`);if(r.status===200||r.status===201)item=x}if(!item?.id)throw new Error("OneDrive upload did not return the completed file item.");const reg=await service.from("onedrive_file_registry").upsert({owner_user_id:uid,drive_id:c.drive_id,drive_item_id:item.id,parent_drive_item_id:p.id,name:item.name??name,one_drive_path:item.parentReference?.path?`${item.parentReference.path}/${item.name}`:null,web_url:item.webUrl??null,client_id:b.clientId,area:b.area??"other",financial_year:b.financialYear??null,filing_period:b.filingPeriod??null,classification_status:"classified",updated_at:new Date().toISOString()},{onConflict:"drive_id,drive_item_id"}).select().single();if(reg.error)throw new Error("OneDrive file uploaded but registry metadata could not be recorded.");return{item,registry:reg.data,parentDriveItemId:p.id}}
async function user(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;const {data,error}=await service.auth.getUser(h.slice(7).trim());return error||!data.user?null:data.user}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST requests only."},405);try{const u=await user(req);if(!u)return json({error:"Authentication required."},401);const {data:p}=await service.from("profiles").select("role,active").eq("id",u.id).maybeSingle();if(!p?.active||!["admin","staff"].includes(p.role))return json({error:"Staff access required."},403);const b=await req.json();if(String(b.operation??"")==="upload_from_supabase")return json({success:true,...await uploadFromSupabase(u.id,b)});return json({error:"Unsupported operation."},400)}catch(e){return json({error:e instanceof Error?e.message:"Filing storage operation failed."},500)}});
