import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const CLIENT_ID=Deno.env.get("MICROSOFT_ONEDRIVE_CLIENT_ID");
const CLIENT_SECRET=Deno.env.get("MICROSOFT_ONEDRIVE_CLIENT_SECRET");
const ENCRYPTION_KEY=Deno.env.get("MICROSOFT_ONEDRIVE_TOKEN_ENCRYPTION_KEY");
const WEBHOOK_URL=`${SUPABASE_URL}/functions/v1/onedrive-sync`;
const service=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json"}});
const b64url=(bytes:Uint8Array)=>{let b="";for(const x of bytes)b+=String.fromCharCode(x);return btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")};
const fromB64url=(v:string)=>{const p=v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-(v.length%4))%4);const b=atob(p),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a};
const utf8=(v:string)=>new TextEncoder().encode(v);
async function deriveKey(s:string){const d=await crypto.subtle.digest("SHA-256",utf8(s));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["encrypt","decrypt"])}
async function decryptCredential(blob:string,iv:string){if(!ENCRYPTION_KEY)throw new Error("OneDrive encryption key is not configured.");const key=await deriveKey(ENCRYPTION_KEY);const p=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64url(iv)},key,fromB64url(blob));return JSON.parse(new TextDecoder().decode(new Uint8Array(p)))}
async function encryptCredential(c:unknown){if(!ENCRYPTION_KEY)throw new Error("OneDrive encryption key is not configured.");const key=await deriveKey(ENCRYPTION_KEY),iv=crypto.getRandomValues(new Uint8Array(12)),e=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,utf8(JSON.stringify(c)));return{blob:b64url(new Uint8Array(e)),iv:b64url(iv)}}
async function graphToken(c:any){if(!CLIENT_ID||!CLIENT_SECRET)throw new Error("OneDrive configuration is incomplete.");const cred=await decryptCredential(c.credential_blob,c.credential_iv);const obtained=Date.parse(String(cred.obtained_at??"2000-01-01T00:00:00.000Z")),expires=Number(cred.expires_in??3600),refresh=!cred.access_token||!Number.isFinite(obtained)||Date.now()>=obtained+expires*1000-120000;if(!refresh)return String(cred.access_token);if(!cred.refresh_token)throw new Error("OneDrive refresh token is unavailable. Reconnect OneDrive.");const r=await fetch("https://login.microsoftonline.com/consumers/oauth2/v2.0/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token:String(cred.refresh_token),grant_type:"refresh_token",scope:"openid profile offline_access User.Read Files.ReadWrite"})}),b=await r.json().catch(()=>({}));if(!r.ok||!b.access_token)throw new Error("OneDrive authorization expired. Reconnect OneDrive.");const next={access_token:String(b.access_token),refresh_token:String(b.refresh_token??cred.refresh_token),token_type:b.token_type??cred.token_type??"Bearer",expires_in:b.expires_in??3600,obtained_at:new Date().toISOString()},e=await encryptCredential(next);await service.from("storage_connections").update({credential_blob:e.blob,credential_iv:e.iv,updated_at:new Date().toISOString(),last_verified_at:new Date().toISOString(),status:"connected"}).eq("id",c.id);return next.access_token}
async function graph(token:string,urlOrPath:string,init:RequestInit={}){const url=urlOrPath.startsWith("http")?urlOrPath:`https://graph.microsoft.com/v1.0${urlOrPath}`;const r=await fetch(url,{...init,headers:{Accept:"application/json",Authorization:`Bearer ${token}`,...(init.headers??{})}});const text=await r.text();let b:any=null;try{b=text?JSON.parse(text):null}catch{}if(!r.ok){const e=new Error(b?.error?.message??`Microsoft Graph request failed (${r.status}).`);(e as any).status=r.status;(e as any).body=b;(e as any).headers=r.headers;throw e}return b}
async function connection(ownerUserId:string){const {data,error}=await service.from("storage_connections").select("id,owner_user_id,provider_user_id,provider_email,drive_id,status,credential_blob,credential_iv").eq("owner_user_id",ownerUserId).eq("provider","onedrive").maybeSingle();if(error||!data)throw new Error("OneDrive is not connected.");if(data.status!=="connected")throw new Error("The OneDrive connection is not active.");return data}
async function stateByDrive(driveId:string){const {data,error}=await service.from("onedrive_sync_state").select("*").eq("drive_id",driveId).maybeSingle();if(error||!data)throw new Error("OneDrive sync state is not initialized.");return data}
async function stateBySubscription(subscriptionId:string){const {data,error}=await service.from("onedrive_sync_state").select("*").eq("subscription_id",subscriptionId).maybeSingle();if(error||!data)throw new Error("Unknown OneDrive subscription.");return data}
async function markError(id:string,message:string){await service.from("onedrive_sync_state").update({status:"error",last_error:message.slice(0,2000),updated_at:new Date().toISOString()}).eq("id",id)}
async function deltaLatest(token:string,userId:string){const b=await graph(token,`/users/${encodeURIComponent(userId)}/drive/root/delta?token=latest`);return String(b?.["@odata.deltaLink"]??"")}
async function markDeleted(state:any,driveItemId:string,source:string){const {data:rows}=await service.from("onedrive_file_registry").select("id,document_id,name,client_id,deleted_at").eq("drive_id",state.drive_id).eq("drive_item_id",driveItemId).limit(20);for(const row of rows??[]){const now=new Date().toISOString();if(row.document_id&&!row.deleted_at){await service.from("documents").update({deleted_at:now,updated_at:now}).eq("id",row.document_id).is("deleted_at",null);await service.from("audit_logs").insert({actor_id:null,client_id:row.client_id??null,action:"document_deleted_external",entity_type:"document",entity_id:row.document_id,metadata:{source,drive_id:state.drive_id,drive_item_id:driveItemId,name:row.name}})}await service.from("onedrive_file_registry").update({deleted_at:now,deletion_source:source,classification_status:"deleted_externally",updated_at:now}).eq("id",row.id)}}
async function applyDeltaPage(state:any,items:any[]){for(const item of items??[]){if(item?.deleted&&item.id)await markDeleted(state,String(item.id),"onedrive");}}
async function syncDrive(state:any,forceFull=false){const c=await connection(state.owner_user_id),token=await graphToken(c);let url=forceFull||!state.delta_link?`/users/${encodeURIComponent(c.provider_user_id)}/drive/root/delta`:state.delta_link;let lastDelta="";try{for(let page=0;page<500;page++){const b=await graph(token,url);await applyDeltaPage(state,b?.value??[]);if(b?.["@odata.nextLink"]){url=b["@odata.nextLink"];continue}lastDelta=String(b?.["@odata.deltaLink"]??"");break}if(!lastDelta)throw new Error("OneDrive delta did not return a deltaLink.");await service.from("onedrive_sync_state").update({delta_link:lastDelta,last_sync_at:new Date().toISOString(),last_error:null,status:"connected",updated_at:new Date().toISOString()}).eq("id",state.id);return{success:true,deltaLink:lastDelta}}catch(e){if((e as any)?.status===410||String((e as any)?.message??"").includes("410")){return await fullReconcile(state,token,c)}throw e}}
async function fullReconcile(state:any,token:string,c:any){let url=`/users/${encodeURIComponent(c.provider_user_id)}/drive/root/delta`,live=new Set<string>(),lastDelta="";for(let page=0;page<500;page++){const b=await graph(token,url);for(const item of b?.value??[]){if(item?.id&&!item.deleted)live.add(String(item.id));}if(b?.["@odata.nextLink"]){url=b["@odata.nextLink"];continue}lastDelta=String(b?.["@odata.deltaLink"]??"");break}if(!lastDelta)throw new Error("Full OneDrive reconciliation did not return a deltaLink.");const {data:rows}=await service.from("onedrive_file_registry").select("id,drive_item_id,document_id,name,client_id,deleted_at").eq("drive_id",state.drive_id).is("deleted_at",null).limit(5000);for(const row of rows??[]){if(!live.has(String(row.drive_item_id)))await markDeleted(state,String(row.drive_item_id),"onedrive_reconcile")}const now=new Date().toISOString();await service.from("onedrive_sync_state").update({delta_link:lastDelta,last_sync_at:now,last_full_reconcile_at:now,last_error:null,status:"connected",updated_at:now}).eq("id",state.id);return{success:true,reconciled:true,checkedRegistryRows:(rows??[]).length}}
async function createOrRenewSubscription(state:any,renewOnly=false){const c=await connection(state.owner_user_id),token=await graphToken(c),now=Date.now(),expires=new Date(now+6*24*60*60*1000).toISOString(),resource=`/users/${encodeURIComponent(c.provider_user_id)}/drive/root`;if(state.subscription_id&&!renewOnly){try{const current=await graph(token,`/subscriptions/${encodeURIComponent(state.subscription_id)}`);if(current?.expirationDateTime&&Date.parse(current.expirationDateTime)>now+2*24*60*60*1000){return current}}catch{}}if(state.subscription_id){try{const renewed=await graph(token,`/subscriptions/${encodeURIComponent(state.subscription_id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expirationDateTime:expires})});await service.from("onedrive_sync_state").update({subscription_expiration_at:renewed.expirationDateTime,status:"connected",last_error:null,updated_at:new Date().toISOString()}).eq("id",state.id);return renewed}catch{}}const clientState=state.client_state||crypto.randomUUID()+crypto.randomUUID();const created=await graph(token,"/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({changeType:"updated",notificationUrl:WEBHOOK_URL,lifecycleNotificationUrl:WEBHOOK_URL,resource,expirationDateTime:expires,clientState})});const deltaLink=await deltaLatest(token,c.provider_user_id);await service.from("onedrive_sync_state").update({subscription_id:created.id,subscription_expiration_at:created.expirationDateTime,client_state:clientState,delta_link:deltaLink,status:"connected",last_error:null,updated_at:new Date().toISOString()}).eq("id",state.id);return created}
async function ensureState(ownerUserId:string){const c=await connection(ownerUserId);let {data}=await service.from("onedrive_sync_state").select("*").eq("owner_user_id",ownerUserId).eq("drive_id",c.drive_id).maybeSingle();if(!data){const clientState=crypto.randomUUID()+crypto.randomUUID();const ins=await service.from("onedrive_sync_state").insert({owner_user_id:ownerUserId,drive_id:c.drive_id,client_state,status:"initializing"}).select().single();if(ins.error)throw ins.error;data=ins.data}return data}
async function requireStaff(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;const {data,error}=await service.auth.getUser(h.slice(7).trim());if(error||!data.user)return null;const {data:p}=await service.from("profiles").select("role,active").eq("id",data.user.id).maybeSingle();return p?.active&&["admin","staff"].includes(p.role)?data.user:null}
async function maintenanceAllowed(req:Request){const key=req.headers.get("x-onedrive-sync-key");if(!key)return false;const {data}=await service.from("onedrive_sync_state").select("id").eq("client_state",key).limit(1);return !!data?.length}
async function handleWebhook(req:Request){const u=new URL(req.url),validation=u.searchParams.get("validationToken");if(validation!==null)return new Response(validation,{status:200,headers:{"Content-Type":"text/plain; charset=utf-8"}});const body=await req.json().catch(()=>({}));const notes=Array.isArray(body?.value)?body.value:[];for(const n of notes){try{const state=await stateBySubscription(String(n.subscriptionId??""));if(String(n.clientState??"")!==String(state.client_state))continue;await service.from("onedrive_sync_state").update({last_notification_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",state.id);EdgeRuntime.waitUntil((async()=>{try{await syncDrive(state,false);if(state.subscription_expiration_at&&Date.parse(state.subscription_expiration_at)<Date.now()+2*24*60*60*1000)await createOrRenewSubscription(state,true)}catch(e){await markError(state.id,e instanceof Error?e.message:"OneDrive notification processing failed")}})());}catch(e){console.error("notification ignored",e)}}return new Response("",{status:202})}
Deno.serve(async(req:Request)=>{try{if(req.method!=="POST")return req.method==="OPTIONS"?new Response("",{status:204}):json({error:"POST requests only."},405);const url=new URL(req.url);if(url.searchParams.has("validationToken")||req.headers.get("content-type")?.includes("text/plain"))return await handleWebhook(req);const body=await req.json().catch(()=>({})),op=String(body.operation??"");if(op==="maintenance"){if(!(await maintenanceAllowed(req)))return json({error:"Unauthorized."},401);const {data:states}=await service.from("onedrive_sync_state").select("*").eq("status","connected").limit(50);const results=[];for(const s of states??[]){try{const c=await connection(s.owner_user_id);if(s.subscription_expiration_at&&Date.parse(s.subscription_expiration_at)<Date.now()+2*24*60*60*1000)await createOrRenewSubscription(s,true);const fresh=await stateByDrive(s.drive_id);const fullDue=!fresh.last_full_reconcile_at||Date.parse(String(fresh.last_full_reconcile_at))<Date.now()-24*60*60*1000;results.push(fullDue?await fullReconcile(fresh,await graphToken(c),c):await syncDrive(fresh,false))}catch(e){await markError(s.id,e instanceof Error?e.message:"Maintenance failed");results.push({success:false,error:e instanceof Error?e.message:"Maintenance failed"})}}return json({success:true,results})}const user=await requireStaff(req);if(!user)return json({error:"Staff access required."},401);if(op==="subscribe"){const state=await ensureState(user.id);const subscription=await createOrRenewSubscription(state,false);return json({success:true,subscription})}if(op==="sync"){const state=await ensureState(user.id);return json(await syncDrive(state,false))}if(op==="reconcile"){const state=await ensureState(user.id);const c=await connection(user.id),token=await graphToken(c);return json(await fullReconcile(state,token,c))}if(op==="status"){const state=await ensureState(user.id);return json({success:true,driveId:state.drive_id,status:state.status,subscriptionId:state.subscription_id,subscriptionExpirationAt:state.subscription_expiration_at,lastSyncAt:state.last_sync_at,lastNotificationAt:state.last_notification_at,lastFullReconcileAt:state.last_full_reconcile_at,lastError:state.last_error})}return json({error:"Unsupported operation."},400)}catch(e){console.error("onedrive-sync error",e);return json({error:e instanceof Error?e.message:"OneDrive sync failed."},500)}});