import { createClient as createSupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "../config.js";
const supabase=createSupabaseClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const MARKER="kka-tab-session:admin";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function stableSession(){for(let i=0;i<4;i++){const {data:{session}}=await supabase.auth.getSession();if(session?.user)return session;if(i<3)await sleep(250)}return null}
async function profile(id){for(let i=0;i<3;i++){const {data,error}=await supabase.from("profiles").select("role,active").eq("id",id).maybeSingle();if(!error&&data)return data;if(i<2)await sleep(250)}return null}
async function root(){try{sessionStorage.removeItem(MARKER)}catch{};window.location.replace("../")}
async function boot(){const session=await stableSession();if(!session?.user)return root();const p=await profile(session.user.id);if(!p?.active){await supabase.auth.signOut({scope:"local"}).catch(()=>{});return root()}if(p.role!=="admin"&&p.role!=="staff"){window.location.replace("../client/");return}try{sessionStorage.setItem(MARKER,String(Date.now()));sessionStorage.setItem("kka-auth-handoff","admin")}catch{};await import("../diagnostic-logger.js?v=20260924-authbridge1");await import("../theme.js?v=20260914-2");await import("../operation-feedback.js?v=20260915-2");await import("../session-route-transition.js?v=20260916-route3");await import("../session-security.js?v=20260924-authbridge1");await import("../session-settings.js?v=20260916-session-settings1");await import("../dashboard-live.js?v=20260915-countfix1");await import("../portal-access-request.js?v=20260915-legal1");await import("../portal-access-admin.js?v=20260914-5");await import("../staff-access.js?v=20260910-1");await import("../storage-view.js?v=20260914-1");await import("../storage-monitor.js?v=20260915-stable1");await import("../document-uploader.js?v=20260920-upload6");await import("../filing-structure-uploader.js?v=20260915-filing2");await import("../documents-browser.js?v=20260920-docbrowser8");await import("../onedrive-directory.js?v=20260920-14");await import("../pan-assessment.js?v=20260910-pan2");await import("../review-queue.js?v=20260915-review2");await import("../ui-search-lite.js?v=20260910-1");await import("../manual-client-search.js?v=20260924-search3");await import("../audit-trail.js?v=20260914-1");await import("../client-access-status.js?v=20260920-accessstatus2");await import("../filing-structure-admin.js?v=20260915-filing1");await import("../nav-bridge.js?v=20260916-nav4");await import("../mobile-menu.js?v=20260916-menu1");await import("../admin-portal-feedback.js?v=20260916-admin-feedback3");await import("../app.js?v=20260920-2fa1");await import("../admin-hash-router.js?v=20260916-hash1");await import("../admin/family-client-bridge.js?v=20260924-family7");await import("../admin/client-creation.js?v=20260920-familyfix2")}
void boot().catch(e=>{console.error("[KKA auth bridge] admin bootstrap failed",e);try{window.KKALog?.error?.("auth_bridge_boot","Admin portal core bootstrap failed",{message:e?.message||String(e)})}catch{}});
